package aero.developer.bagnet.objects;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "BagTag".
 */
public class BagTag  implements Parcelable {

    private Long id;
    private String datetime;
    private String trackingpoint;
    private String containerid;
    private String bagtag;
    private String flightnum;
    private String flighttype;
    private String flightdate;
    private boolean synced;
    private boolean locked;
    private String errorMsg;
    private String pnr;
    private String passenger_last_name;
    private String passenger_first_name;
    private String inbound_airline_code;
    private String inbound_flight_date;
    private String origin_airport;
    private String outbound_airline_code;
    private String outbound_flight_date;
    private String destination_airport;
    private String inbound_flight_num;
    private String outbound_flight_num;


    private boolean showProgressBar = true;
    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BagTag() {

    }





    public boolean isShowProgressBar() {
        return showProgressBar;
    }

    public void setShowProgressBar(boolean showProgressBar) {
        this.showProgressBar = showProgressBar;

    }

    public BagTag(Long id) {
        this.id = id;
    }

    public BagTag(Long id, String datetime, String trackingpoint, String containerid, String bagtag, String flightnum, String flighttype, String flightdate, boolean synced, boolean locked, String errorMsg, String pnr, String passenger_last_name, String passenger_first_name, String inbound_airline_code, String inbound_flight_date, String origin_airport, String outbound_airline_code, String outbound_flight_date, String destination_airport, String inbound_flight_num, String outbound_flight_num) {
        this.id = id;
        this.datetime = datetime;
        this.trackingpoint = trackingpoint;
        this.containerid = containerid;
        this.bagtag = bagtag;
        this.flightnum = flightnum;
        this.flighttype = flighttype;
        this.flightdate = flightdate;
        this.synced = synced;
        this.locked = locked;
        this.errorMsg = errorMsg;
        this.pnr = pnr;
        this.passenger_last_name = passenger_last_name;
        this.passenger_first_name = passenger_first_name;
        this.inbound_airline_code = inbound_airline_code;
        this.inbound_flight_date = inbound_flight_date;
        this.origin_airport = origin_airport;
        this.outbound_airline_code = outbound_airline_code;
        this.outbound_flight_date = outbound_flight_date;
        this.destination_airport = destination_airport;
        this.inbound_flight_num = inbound_flight_num;
        this.outbound_flight_num = outbound_flight_num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDatetime() {
        return datetime;
    }

    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    public String getTrackingpoint() {
        return trackingpoint;
    }

    public void setTrackingpoint(String trackingpoint) {
        this.trackingpoint = trackingpoint;
    }

    public String getContainerid() {
        return containerid;
    }

    public void setContainerid(String containerid) {
        this.containerid = containerid;
    }

    public String getBagtag() {
        return bagtag;
    }

    public void setBagtag(String bagtag) {
        this.bagtag = bagtag;
    }

    public String getFlightnum() {
        return flightnum;
    }

    public void setFlightnum(String flightnum) {
        this.flightnum = flightnum;
    }

    public String getFlighttype() {
        return flighttype;
    }

    public void setFlighttype(String flighttype) {
        this.flighttype = flighttype;
    }

    public String getFlightdate() {
        return flightdate;
    }

    public void setFlightdate(String flightdate) {
        this.flightdate = flightdate;
    }

    public boolean getSynced() {
        return synced;
    }

    public void setSynced(boolean synced) {
        this.synced = synced;
    }

    public boolean getLocked() {
        return locked;
    }

    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    public String getErrorMsg() {
        return errorMsg;
    }

    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    public String getPnr() {
        return pnr;
    }

    public void setPnr(String pnr) {
        this.pnr = pnr;
    }

    public String getPassenger_last_name() {
        return passenger_last_name;
    }

    public void setPassenger_last_name(String passenger_last_name) {
        this.passenger_last_name = passenger_last_name;
    }

    public String getPassenger_first_name() {
        return passenger_first_name;
    }

    public void setPassenger_first_name(String passenger_first_name) {
        this.passenger_first_name = passenger_first_name;
    }

    public String getInbound_airline_code() {
        return inbound_airline_code;
    }

    public void setInbound_airline_code(String inbound_airline_code) {
        this.inbound_airline_code = inbound_airline_code;
    }

    public String getInbound_flight_date() {
        return inbound_flight_date;
    }

    public void setInbound_flight_date(String inbound_flight_date) {
        this.inbound_flight_date = inbound_flight_date;
    }

    public String getOrigin_airport() {
        return origin_airport;
    }

    public void setOrigin_airport(String origin_airport) {
        this.origin_airport = origin_airport;
    }

    public String getOutbound_airline_code() {
        return outbound_airline_code;
    }

    public void setOutbound_airline_code(String outbound_airline_code) {
        this.outbound_airline_code = outbound_airline_code;
    }

    public String getOutbound_flight_date() {
        return outbound_flight_date;
    }

    public void setOutbound_flight_date(String outbound_flight_date) {
        this.outbound_flight_date = outbound_flight_date;
    }

    public String getDestination_airport() {
        return destination_airport;
    }

    public void setDestination_airport(String destination_airport) {
        this.destination_airport = destination_airport;
    }

    public String getInbound_flight_num() {
        return inbound_flight_num;
    }

    public void setInbound_flight_num(String inbound_flight_num) {
        this.inbound_flight_num = inbound_flight_num;
    }

    public String getOutbound_flight_num() {
        return outbound_flight_num;
    }

    public void setOutbound_flight_num(String outbound_flight_num) {
        this.outbound_flight_num = outbound_flight_num;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "BagTag{" +
                "id=" + id +
                ", datetime='" + datetime + '\'' +
                ", trackingpoint='" + trackingpoint + '\'' +
                ", containerid='" + containerid + '\'' +
                ", bagtag='" + bagtag + '\'' +
                ", flightnum='" + flightnum + '\'' +
                ", flighttype='" + flighttype + '\'' +
                ", flightdate='" + flightdate + '\'' +
                ", synced=" + synced +
                ", locked=" + locked +
                ", errorMsg='" + errorMsg + '\'' +
                ", pnr='" + pnr + '\'' +
                ", passenger_last_name='" + passenger_last_name + '\'' +
                ", passenger_first_name='" + passenger_first_name + '\'' +
                ", inbound_airline_code='" + inbound_airline_code + '\'' +
                ", inbound_flight_date='" + inbound_flight_date + '\'' +
                ", origin_airport='" + origin_airport + '\'' +
                ", outbound_airline_code='" + outbound_airline_code + '\'' +
                ", outbound_flight_date='" + outbound_flight_date + '\'' +
                ", destination_airport='" + destination_airport + '\'' +
                ", inbound_flight_num='" + inbound_flight_num + '\'' +
                ", outbound_flight_num='" + outbound_flight_num + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        BagTag bagTag = (BagTag) o;

        if (!trackingpoint.equals(bagTag.trackingpoint)) return false;
        if (containerid != null ? !containerid.equals(bagTag.containerid) : bagTag.containerid != null)
            return false;
        return bagtag != null ? bagtag.equals(bagTag.bagtag) : bagTag.bagtag == null;

    }

    @Override
    public int hashCode() {
        int result = trackingpoint.hashCode();
        result = 31 * result + (containerid != null ? containerid.hashCode() : 0);
        result = 31 * result + (bagtag != null ? bagtag.hashCode() : 0);
        return result;
    }
    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.datetime);
        dest.writeString(this.trackingpoint);
        dest.writeString(this.containerid);
        dest.writeString(this.bagtag);
        dest.writeString(this.flightnum);
        dest.writeString(this.flighttype);
        dest.writeString(this.flightdate);
        dest.writeByte(this.synced ? (byte) 1 : (byte) 0);
        dest.writeByte(this.locked ? (byte) 1 : (byte) 0);
        dest.writeString(this.errorMsg);
        dest.writeString(this.pnr);
        dest.writeString(this.passenger_last_name);
        dest.writeString(this.passenger_first_name);
        dest.writeString(this.inbound_airline_code);
        dest.writeString(this.inbound_flight_date);
        dest.writeString(this.origin_airport);
        dest.writeString(this.outbound_airline_code);
        dest.writeString(this.outbound_flight_date);
        dest.writeString(this.destination_airport);
        dest.writeString(this.inbound_flight_num);
        dest.writeString(this.outbound_flight_num);
    }

    protected BagTag(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.datetime = in.readString();
        this.trackingpoint = in.readString();
        this.containerid = in.readString();
        this.bagtag = in.readString();
        this.flightnum = in.readString();
        this.flighttype = in.readString();
        this.flightdate = in.readString();
        this.synced = in.readByte() != 0;
        this.locked = in.readByte() != 0;
        this.errorMsg = in.readString();
        this.pnr = in.readString();
        this.passenger_last_name = in.readString();
        this.passenger_first_name = in.readString();
        this.inbound_airline_code = in.readString();
        this.inbound_flight_date = in.readString();
        this.origin_airport = in.readString();
        this.outbound_airline_code = in.readString();
        this.outbound_flight_date = in.readString();
        this.destination_airport = in.readString();
        this.inbound_flight_num = in.readString();
        this.outbound_flight_num = in.readString();
    }

    public static final Parcelable.Creator<BagTag> CREATOR = new Parcelable.Creator<BagTag>() {
        @Override
        public BagTag createFromParcel(Parcel source) {
            return new BagTag(source);
        }

        @Override
        public BagTag[] newArray(int size) {
            return new BagTag[size];
        }
    };

}
