package aero.developer.bagnet.objects;

public enum EventStatus {
    CHECKED_IN, PAX_BOARDED, SCREENED, SCREENING_PASSED, SCREENING_FAILED, SORTED, LOADED_IN_CONTAINER, LOADED_ON_AIRCRAFT, OFFLOADED, EXPECTED, REROUTED, REFLIGHTED, CANCELLED, MISHANDLED, OND
}
